// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjFnoPxJhkE9Ag6Xw0BGw9RS6nC_2mls',
    appId: '1:241671014791:android:13ab951a9dc87bf72c6b22',
    messagingSenderId: '241671014791',
    projectId: 'ecommerce-hive-f01fd',
    storageBucket: 'ecommerce-hive-f01fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTUzN9uoGISkANlVYPT-gZMYaCg5P0q8',
    appId: '1:241671014791:ios:b3cc541f291c9b052c6b22',
    messagingSenderId: '241671014791',
    projectId: 'ecommerce-hive-f01fd',
    storageBucket: 'ecommerce-hive-f01fd.appspot.com',
    androidClientId: '241671014791-9md9fpb6t3vdn43e998one2etnmve7ir.apps.googleusercontent.com',
    iosClientId: '241671014791-m5f9s6jva1oq8atciljttjejfm7oonse.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommereHiveJavaprint',
  );

}